spring:
  data:
    rest:
      base-path: /api/
  datasource:
    url: jdbc:mysql://localhost/user_service?useSSL=false
    username: root
    password: asanka12345
    validation-query: SELECT 1
    test-on-borrow: true
  jpa:
    show_sql: false
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5
    properties:
      hibernate:
        cache:
          use_second_level_cache: false
          use_query_cache: false
        generate_statistics: false
  application:
    name: accounts_service
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5
server:
  port: 8081